heat_template_version: 2013-05-23
description: AutoScaling Wordpress
parameters:
  web-image:
    type: string
    description: Image used for web servers
    default: CentOS-7 64Bits
  key:
    type: string
    description: SSH key to connect to the servers
    default: Ubuntu Victor
  web-flavor:
    type: string
    description: flavor used by the web servers
    default: small.2GB
  subnet_id:
    type: string
    description: subnet on which the load balancer will be located
    default: 2a4ddc88-57d3-4b6c-816e-86d2b623eeee


resources:

  web-monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  web-pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{get_resource: web-monitor}]
      subnet_id: {get_param: subnet_id}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80
  web-lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: web-pool}


  web_server_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 5
      resource:
        type: web_server.yaml
        properties:
          flavor: {get_param: web-flavor}
          image: {get_param: web-image}
          key_name: {get_param: key}
          pool_id: {get_resource: web-pool}



  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: web_server_group}
      cooldown: 10
      scaling_adjustment: 1
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: web_server_group}
      cooldown: 10
      scaling_adjustment: -1
  web_cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 80% for 1 minute
      meter_name: cpu_util
      statistic: avg
      period: 10
      evaluation_periods: 1
      threshold: 40
      alarm_actions:
        - {get_attr: [web_server_scaleup_policy, alarm_url]}
      comparison_operator: gt
  web_cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if the average CPU < 30% for 1 minutes
      meter_name: cpu_util
      statistic: avg
      period: 10
      evaluation_periods: 1
      threshold: 30
      alarm_actions:
        - {get_attr: [web_server_scaledown_policy, alarm_url]}
      comparison_operator: lt


outputs:
  wordpress_url:
    value:
      str_replace:
        template: http://url/wordpress
        params:
          url: {get_attr: [web-pool, vip, address]}
    description: The url of wordpress blog
